[package]
documentation = "https://github.com/cross-rs/wiki_assets"
license = "MIT OR Apache-2.0"
name = "sccache"
repository = "https://github.com/cross-rs/wiki_assets"
version = "0.0.0-dev.0"
edition = "2021"
publish = false
